function [presetA, nameStrings, typeStrings] = createPresetAforOSC()
%% The names of these variables are the same as the names of the corresponding OSC messages

%% Preset A
PMparams = [...
    0.0, 1.0, 1.0, 1.0, 0.4, 0.0, ...
    0.0, 0.0, 0.0, 1.0, 0.0, 4.0, ...
    0.0, 0.0, 0.0, 0.0, 4.0, 0.0, ...
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
    0.0, 0.0, 0.0, 0.2, 0.0, 0.0]; 

freqCoarse = [1, 0.5, 1, 0.5, 1, 1]; 

freqFine = [0, 0.01, 0.0, 0.0, 0, 0]; 

outputLevels = [1, 0.5, 0.1, 0.0, 0.0, 0.0]; 

envAmt = [0.0, 0.5, 0.3, 1, 1, 1 ]; 

lfoADepth = [0.0, 0.5, 0.3, 0.2, 0.6, 0.5]; 
        %lfo1Rate, lfo1Amp, lfo1PhaseSpread
        
lfoAParams = [5.10, 0.8, 0.1]; 

         %A, D, S, R, curve
envAmpParams = [0.6, 0.1, 0.7, 0.5]; 
         %A, D, S, R, curve
env1Params = [0.7, 0.9, 1.0, 0.5]; 

misc = 0.9; % StereoSpread

presetA = [PMparams,...
            freqCoarse,...
            freqFine,...
            outputLevels,...
            envAmt,...
            lfoADepth,...
            lfoAParams,...
            envAmpParams,...
            env1Params,...
            misc];


nameStrings = {'/PMparams',...
               '/freqCoarse',...
               '/freqFine',...
               '/outputLevels',...
               '/envAmt',...
               '/lfoADepth',...
               '/lfoAParams',...
               '/envAmpParams',...
               '/env1Params',...
               '/misc'...
               };
               
                
presetComponentLengths = [length(PMparams),...
            length(freqCoarse),...
            length(freqFine),...
            length(outputLevels),...
            length(envAmt),...
            length(lfoADepth),...
            length(lfoAParams),...
            length(envAmpParams),...
            length(env1Params),...
            length(misc)];
        
typeStrings = cell(1,length(presetComponentLengths));
for i = 1:length(presetComponentLengths)
    typeStrings{i}(1:presetComponentLengths(i))  = 'f';
end

end