function [G] = createFreezeSections(G)

figure(4)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
p1 = uipanel('Title','Timbre Controls',...
             'Position',[.05 .05 .425 .9]);
 
G.but_freeze_timbre = uicontrol(p1,'style', 'pushbutton',...
    'string', 'Freeze Timbre',...
    'units', 'normalized',...
    'position', [0.0 0.9 1.0 0.11],...
    'callback', {@timbreButtonCallback},...
    'FontSize', 13);
         
G.togglePMparams = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze PM Params',...
    'units', 'normalized',...
    'position', [0.05 0.8 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleFreqCoarse = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze Freq Coarse',...
    'units', 'normalized',...
    'position', [0.05 0.7 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleFreqFine = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze Freq Fine',...
    'units', 'normalized',...
    'position', [0.05 0.6 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleOutputLevels = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze Output Levels',...
    'units', 'normalized',...
    'position', [0.05 0.5 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleEnvAmt = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze Mod Env Amt',...
    'units', 'normalized',...
    'position', [0.05 0.4 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleLfoADepth = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze LFO A Depth',...
    'units', 'normalized',...
    'position', [0.05 0.3 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleLfoBDepth = uicontrol(p1, 'style', 'checkbox',...
    'string', 'Freeze LFO B Depth',...
    'units', 'normalized',...
    'position', [0.05 0.2 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
p2 = uipanel('Title','Time Controls',...
             'Position',[.5 .05 .45 .9]);
         
        
G.but_freeze_time = uicontrol(p2,'style', 'pushbutton',...
    'string', 'Freeze Time',...
    'units', 'normalized',...
    'position', [0.0 0.9 1.0 0.11],...
    'callback', {@timeButtonCallback},...
    'FontSize', 13);
         
G.toggleLfoAParams = uicontrol(p2, 'style', 'checkbox',...
    'string', 'Freeze LFO A Params',...
    'units', 'normalized',...
    'position', [0.05 0.8 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleLfoBParams = uicontrol(p2, 'style', 'checkbox',...
    'string', 'Freeze LFO B Params',...
    'units', 'normalized',...
    'position', [0.05 0.7 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleEnvAmpParams = uicontrol(p2, 'style', 'checkbox',...
    'string', 'Freeze Amp Env Params',...
    'units', 'normalized',...
    'position', [0.05 0.6 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleEnv1Params = uicontrol(p2, 'style', 'checkbox',...
    'string', 'Freeze Mod Env Params',...
    'units', 'normalized',...
    'position', [0.05 0.5 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

G.toggleMisc = uicontrol(p2, 'style', 'checkbox',...
    'string', 'Freeze Misc Params',...
    'units', 'normalized',...
    'position', [0.05 0.4 0.9 0.1],...
    'callback', {@freezeSectionsCallback},...
    'FontSize', 13);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function timbreButtonCallback (object, eventdata)
% writes continuous mouse position to base workspace
disp('Freeze Timbre Button Clicked')

assignin('base','isTimbreButtonPressed',true)

end

function timeButtonCallback (object, eventdata)
% writes continuous mouse position to base workspace
disp('Freeze Time Button Clicked')

assignin('base','isTimeButtonPressed',true)

end

function freezeSectionsCallback (object, eventdata)
% writes continuous mouse position to base workspace
disp('Freeze Section Toggle Button Clicked')

assignin('base','isFreezeSectionToggled',true)

end