function y = phaseModSynth(freq, mod)

y = zeros(6,100);

for i = (2:2000)
    t = i/1000;
    for j = 1:6
        y(j,i) = sin(2*pi*t*freq(j) + y(1,i-1)*mod(1,j)...
                                    + y(2,i-1)*mod(2,j)...
                                    + y(3,i-1)*mod(3,j)...
                                    + y(4,i-1)*mod(4,j)...
                                    + y(5,i-1)*mod(5,j)...
                                    + y(6,i-1)*mod(6,j)...
                            );
    end
end
end