function y = phaseModSynth(freq, mod)

y = zeros(6,100);

for i = (2:2000)
    t = i/1000;
    for j = 1:6
        y(j,i) = sin(2*pi*t*freq(j) + y(1,i-1)*mod(j,1)...
                                    + y(2,i-1)*mod(j,2)...
                                    + y(3,i-1)*mod(j,3)...
                                    + y(4,i-1)*mod(j,4)...
                                    + y(5,i-1)*mod(j,5)...
                                    + y(6,i-1)*mod(j,6)...
                            );
    end
end
end